### ISSUE TITLE
docs: add a runnable Java and Gradle reduction example

### ISSUE THREAD

**Issue by fly1d** [fly1d/repomin#12]
## Goal

Add one self-contained Java or Gradle workflow to `docs/EXAMPLES.md` so a contributor can run a structured reduction without inventing the command shape.

## Scope

- Use an existing network-free fixture or add a minimal fixture under `benchmarks/`.
- Document the required JDK/Gradle tools and the failure oracle.
- Show the expected minimized payload and report validation command.
- Keep the change documentation-focused; do not change reducer semantics.

## Acceptance criteria

- A clean checkout can follow the example from start to finish.
- The command preserves the original failure signal and rejects a different failure.
- The example states host/Docker trust boundaries and optional tool requirements.
- Relevant tests or benchmark assertions pass, and the changelog is updated.

Please comment before starting. Do not include private source, credentials, or unreleased dependencies.

**Comment by ShravyaHegade** [comment]
Hi @fly1d, I’d like to take this on. Could you assign this issue to me? I’d be happy to work on it and submit a PR.

**Comment by fly1d** [comment]
Thanks for volunteering. I assigned this issue to you. Please keep the change documentation-focused: use the existing network-free Gradle fixture or add a minimal fixture under benchmarks/, show the failure oracle and expected minimized payload, include report validation, and update CHANGELOG.md. Please open a PR when ready; no private source, credentials, or unreleased dependencies.

**Comment by ShravyaHegade** [comment]
Opened PR: https://github.com/fly1d/repomin/pull/15

**Comment by fly1d** [comment]
Maintainer status (2026-08-31): two Gradle example PRs are open for this issue. PR #15 is the assigned implementation and is under review; it needs the Markdown fence completed, the expected minimized payload and report-validation command added, and a rebase onto current `main`. PR #14 covers a similar workflow but currently has full-file CRLF churn, a missing changelog entry, and overlapping scope, so it is also blocked pending coordination. We will merge one clean, canonical example rather than duplicate documentation.

**Comment by fly1d** [comment]
Maintainer update (2026-08-31):

- `main` now includes a standard-library-only documentation preflight (`scripts/check_docs.py`) for UTF-8, LF line endings, and balanced Markdown fences; it runs through `scripts/check_contribution.py` and CI.
- `.gitattributes` keeps common source, fixture, configuration, and documentation files on LF endings across platforms.
- CI run [33351843529](https://github.com/fly1d/repomin/actions/runs/33351843529) is green across the Python/JDK and Windows/macOS/Linux matrix, Action smoke test, offline benchmarks, and wheel/source-distribution checks.

PR #15 remains the assigned canonical implementation and is still awaiting the requested fence closure, exact expected payload list, report-validation command, rebase onto current `main`, and contributor checks. PR #14 remains a duplicate with line-ending churn and is not being merged in parallel. We will review one clean, complete example once the author updates.

**Comment by fly1d** [comment]
Maintainer update (2026-08-31): the reviewed `v0.1.0.dev5` release is available for contributors who want to run the Gradle fixture locally: https://github.com/fly1d/repomin/releases/tag/v0.1.0.dev5\n\nPR #15 remains the assigned canonical implementation and is still awaiting the requested fence closure, exact expected payload list, report-validation command, rebase onto current `main`, and contributor checks. PR #14 remains a duplicate with line-ending churn. We will merge one clean, complete example once the contributor updates.

**Comment by fly1d** [comment]
Maintainer update (2026-08-31): the canonical Gradle example is complete and merged via PR #15. The workflow is verified against `gradle:8.10.2-jdk17` with offline Docker execution, preserves `NoSuchMethodError`, reduces the fixture to `app/build.gradle.kts` and `settings.gradle.kts`, and includes report validation plus trust-boundary guidance.

A follow-up on `main` also hardens the duplicate benchmark documentation with `-Prequired.flag=true`, `--offline`, exact matching, single-concurrency stability, and a Docker-shared output path. Local preflight and the full CI matrix are green. PR #14 was closed as overlapping.

**Comment by fly1d** [comment]
Completed by merged PR #15 and the follow-up reproducibility hardening on `main` (`70047c0`). The canonical Gradle example now meets all acceptance criteria.
